# Dockerfile to run genmod pytest suite
FROM python:3.13

RUN mkdir -p /genmod

COPY requirements.txt /genmod/

RUN pip3 install -r /genmod/requirements.txt

COPY . /genmod

ENV PYTHONPATH=/genmod

WORKDIR /genmod

RUN pip3 install .

ENTRYPOINT ["pytest"]
