# Dockerfile to run genmod pytest suite
FROM ghcr.io/astral-sh/uv:python3.13-alpine

ADD . /app

# Sync the project into a new environment, using the frozen lockfile
WORKDIR /app
RUN uv sync --all-extras --dev

ENTRYPOINT ["uv", "run", "pytest"]
