name: Publish to PyPI

on:
 release:
  types:
   - created

jobs:
 pypi:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv build
      - run: uv publish --trusted-publishing always

 docker-image-CI:
   name: Docker Image CI
   runs-on: ubuntu-latest
   steps:

    - name: Check out git repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Publish server image (Dockerfile-server) to Registry
      uses: docker/build-push-action@v6
      with:
        context: ./
        file: ./Dockerfile
        push: true
        provenance: mode=max
        sbom: true
        tags: "clinicalgenomics/genmod:latest, clinicalgenomics/genmod:${{ github.event.release.tag_name }}"


 deploy-docs:
    name: Deploy Docs to GitHubIO
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repo
       uses: actions/checkout@v4
     - name: Setup environment for docs deployment
       uses: actions/setup-python@v5
       with:
         python-version: 3.x
     - name: Install mkdocs
       run: pip install mkdocs mkdocs-material markdown-include
     - name: Deploy documentation
       run: mkdocs gh-deploy --force

