# Basic CI setup: Lint with ruff
name: Lint

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review, labeled, unlabeled ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Ruff check import sorting
        uses: astral-sh/ruff-action@v1
        with:
          args: "check --select I ."

      - name: Ruff format diff
        uses: astral-sh/ruff-action@v1
        with:
          args: "format --diff ."

