# Basic CI setup: Lint format with ruff
name: Format-check

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review, labeled, unlabeled ]

jobs:
  lint-format:
    name: Ruff includes and format
    runs-on: ubuntu-latest

    steps:
      - name: Ruff check import sorting
        uses: astral-sh/ruff-action@v1
        with:
          args: "check --select I ."

      - name: Ruff format diff
        uses: astral-sh/ruff-action@v1
        with:
          args: "format --diff ."

