# Basic CI setup: Lint with ruff
name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Ruff lint
        uses: astral-sh/ruff-action@v1
        with:
          args: "check ."

      - name: Ruff check import sorting
        uses: astral-sh/ruff-action@v1
        with:
          args: "check --select I ."

      - name: Ruff format diff
        uses: astral-sh/ruff-action@v1
        with:
          args: "format --diff ."

