name: Tests

on:
  pull_request:
  #push:

jobs:
  run-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: "${{github.event.inputs.branch_name}}"
          fetch-depth: 0

      - name: Run Tests
        run: |
          make test

      - name: Run Packaging Test
        run: |
          make test_dist
